[package]
name = "smart_thermostat"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
simple_crypt = "0.2.3"
